/**
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
*
* $Revision: 2958 $
*
* $Header: http://192.100.194.241:8080/svn/ProductTools/JavaTools/AdvancedPRE/trunk/src/stg/pr/beans/ProcessRequestScheduleEntityBean.java 1402 2010-05-06 11:14:41Z kedar $
*
* $Log: /Utilities/PRE/src/stg/pr/beans/ProcessRequestScheduleEntityBean.java $
 * 
 * 11    2/04/09 3:51p Kedarr
 * Added static keyword to a final variable.
 * 
 * 10    9/15/08 10:46a Kedarr
 * Removed the column calendar_class_nm. Also, removed some commented
 * code.
 * 
 * 9     6/15/08 10:52p Kedarr
 * Changes made for a additional column cal_scheduled_time that has been
 * added to the process_request table.
 * 
 * 8     3/23/08 12:39p Kedarr
 * Added the REVISION variables to store the configuration management
 * version number of the class.
 * 
 * 7     3/18/08 3:08p Kedarr
 * Added Email Ids
 * 
 * 6     3/02/07 8:54a Kedarr
 * Added serial version as it is a good practice for serializable objects
 * 
 * 5     7/15/05 2:29p Kedarr
 * Removed All Unused variables. Added a method to return REVISION number.
 * 
 * 4     7/13/05 6:42p Kedarr
 * Check for recur to have a value > 0  is removed.
 * 
 * 3     1/19/05 3:10p Kedarr
 * Advanced PRE
* Revision 1.1  2005/11/03 04:54:42  kedar
* *** empty log message ***
*
 * 
 * 1     11/03/03 12:00p Kedarr
* Revision 1.5  2003/11/01 09:06:41  kedar
* Organized the imports
*
* Revision 1.4  2003/10/29 08:52:46  kedar
* Updated JavaDoc
*
* Revision 1.3  2003/10/29 07:08:09  kedar
* Changes made for changing the Header Information from all the files.
* These files now do belong to Systems Task Group International Ltd.
*
* Revision 1.2  2003/10/23 09:06:46  kedar
* Added Future Scheduling Only column
*
* Revision 1.1  2003/10/23 06:58:41  kedar
* Inital Version Same as VSS
*
 * 
 * *****************  Version 3  *****************
 * User: Kedarr       Date: 9/29/03    Time: 4:47p
 * Updated in $/GMACDev/ProcessRequestEngine/gmac/pr/beans
 * Changes made for start time and end time fields which were newly added.
 * 
 * *****************  Version 2  *****************
 * User: Kedarr       Date: 9/19/03    Time: 10:13a
 * Updated in $/GMACDev/ProcessRequestEngine/gmac/pr/beans
 * Organising Imports
*
*/

/*
*  This Class is generated by WBNew Generic Program written by Kedar.
*  Created on 01/08/2003 09:48:43
*
*  Please Note : checkNull(Object obj) mehtod only checks for Object and not on primitive types
*
*
*/
package stg.pr.beans;

import java.io.Serializable;
import java.sql.Timestamp;

import stg.database.CBeanException;

public class ProcessRequestScheduleEntityBean implements Cloneable, Serializable{

    /**
	 * Serial Version.
	 */
	private static final long serialVersionUID = 4880824256229784468L;
	
	/**
     * Stores the REVISION number of the class from the configuration management tool. 
     */
    public static final String REVISION = "$Revision:: 2958              $";

	public ProcessRequestScheduleEntityBean(){
        super();//Default Constructor given
    }


    private long schId = 0;
    private long oldschId = 0;

    public void setSchId( long schId  ) {
        if (schId <= 0)
        {
            throw new IllegalArgumentException("Schedule ID must be Non-Zero Positive number");
        }
        this.schId = schId ;
    }

    public long getSchId(){
        return schId;
    }


    public void setoldSchId( long oldschId  ) {
        this.oldschId = oldschId ;
    }

    public long getoldSchId(){
        return oldschId;
    }

    private String freqType = null;
    private String oldfreqType = null;

    public void setFreqType( String freqType  ) {
        this.freqType = freqType ;
    }

    public String getFreqType(){
        return freqType;
    }


    public void setoldFreqType( String oldfreqType  ) {
        this.oldfreqType = oldfreqType ;
    }

    public String getoldFreqType(){
        return oldfreqType;
    }

    private long recur = 0;
    private long oldrecur = 0;

    public void setRecur( long recur  ) {
        this.recur = recur ;
    }

    public long getRecur(){
        return recur;
    }


    public void setoldRecur( long oldrecur  ) {
        this.oldrecur = oldrecur ;
    }

    public long getoldRecur(){
        return oldrecur;
    }

    private Timestamp startDt = null;
    private Timestamp oldstartDt = null;

    public void setStartDt( Timestamp startDt  ) {
        this.startDt = startDt ;
    }

    public Timestamp getStartDt(){
        return startDt;
    }


    public void setoldStartDt( Timestamp oldstartDt  ) {
        this.oldstartDt = oldstartDt ;
    }

    public Timestamp getoldStartDt(){
        return oldstartDt;
    }

    private String schStat = null;
    private String oldschStat = null;

    public void setSchStat( String schStat  ) {
        this.schStat = schStat ;
    }

    public String getSchStat(){
        return schStat;
    }


    public void setoldSchStat( String oldschStat  ) {
        this.oldschStat = oldschStat ;
    }

    public String getoldSchStat(){
        return oldschStat;
    }

    private String userId = null;
    private String olduserId = null;

    public void setUserId( String userId  ) {
        this.userId = userId ;
    }

    public String getUserId(){
        return userId;
    }


    public void setoldUserId( String olduserId  ) {
        this.olduserId = olduserId ;
    }

    public String getoldUserId(){
        return olduserId;
    }

    private String onWeekDay = null;
    private String oldonWeekDay = null;

    public void setOnWeekDay( String onWeekDay  ) {
        this.onWeekDay = onWeekDay ;
    }

    public String getOnWeekDay(){
        return onWeekDay;
    }


    public void setoldOnWeekDay( String oldonWeekDay  ) {
        this.oldonWeekDay = oldonWeekDay ;
    }

    public String getoldOnWeekDay(){
        return oldonWeekDay;
    }

    private Timestamp endDt = null;
    private Timestamp oldendDt = null;

    public void setEndDt( Timestamp endDt  ) {
        this.endDt = endDt ;
    }

    public Timestamp getEndDt(){
        return endDt;
    }


    public void setoldEndDt( Timestamp oldendDt  ) {
        this.oldendDt = oldendDt ;
    }

    public Timestamp getoldEndDt(){
        return oldendDt;
    }

    private long endOccur = 0;
    private long oldendOccur = 0;

    public void setEndOccur( long endOccur  ) {
        this.endOccur = endOccur ;
    }

    public long getEndOccur(){
        return endOccur;
    }


    public void setoldEndOccur( long oldendOccur  ) {
        this.oldendOccur = oldendOccur ;
    }

    public long getoldEndOccur(){
        return oldendOccur;
    }

    private Timestamp entryDt = null;
    private Timestamp oldentryDt = null;

    public void setEntryDt( Timestamp entryDt  ) {
        this.entryDt = entryDt ;
    }

    public Timestamp getEntryDt(){
        return entryDt;
    }


    public void setoldEntryDt( Timestamp oldentryDt  ) {
        this.oldentryDt = oldentryDt ;
    }

    public Timestamp getoldEntryDt(){
        return oldentryDt;
    }

    private String modifyId = null;
    private String oldmodifyId = null;

    public void setModifyId( String modifyId  ) {
        this.modifyId = modifyId ;
    }

    public String getModifyId(){
        return modifyId;
    }


    public void setoldModifyId( String oldmodifyId  ) {
        this.oldmodifyId = oldmodifyId ;
    }

    public String getoldModifyId(){
        return oldmodifyId;
    }

    private Timestamp modifyDt = null;
    private Timestamp oldmodifyDt = null;

    public void setModifyDt( Timestamp modifyDt  ) {
        this.modifyDt = modifyDt ;
    }

    public Timestamp getModifyDt(){
        return modifyDt;
    }


    public void setoldModifyDt( Timestamp oldmodifyDt  ) {
        this.oldmodifyDt = oldmodifyDt ;
    }

    public Timestamp getoldModifyDt(){
        return oldmodifyDt;
    }

    private String reqStat = null;
    private String oldreqStat = null;

    public void setReqStat( String reqStat  ) {
        this.reqStat = reqStat ;
    }

    public String getReqStat(){
        return reqStat;
    }


    public void setoldReqStat( String oldreqStat  ) {
        this.oldreqStat = oldreqStat ;
    }

    public String getoldReqStat(){
        return oldreqStat;
    }
    
    private long occurCounter = 0;
    private long oldoccurCounter = 0;
    
    public void setOccurCounter(long occurCounter)
    {
        this.occurCounter = occurCounter;
    }

    public void setoldOccurCounter(long oldoccurCounter)
    {
        this.oldoccurCounter = oldoccurCounter;
    }
    
    public long getOccurCounter()
    {
        return(this.occurCounter);
    }

    public long getoldoccurCounter()
    {
        return(this.oldoccurCounter);
    }
    
    private String processClassNm = null;
    private String oldprocessClassNm = null;
    
    public void setProcessClassNm(String processClassNm)
    {
        this.processClassNm = processClassNm;
    }
    
    public void setoldProcessClassNm(String oldprocessClassNm)
    {
        this.oldprocessClassNm = oldprocessClassNm;
    }
    
    public String getProcessClassNm()
    {
        return(this.processClassNm);
    }
    
    public String getoldProcessClassNm()
    {
        return(this.oldprocessClassNm);
    }
    
    private Timestamp startTime;
    private Timestamp oldstartTime;

    public Timestamp getoldStartTime()
    {
        return oldstartTime;
    }

    public Timestamp getStartTime()
    {
        return startTime;
    }

    public void setoldStartTime(Timestamp timestamp)
    {
        oldstartTime = timestamp;
    }

    public void setStartTime(Timestamp timestamp)
    {
        startTime = timestamp;
    }
    
    private Timestamp endTime;
    private Timestamp oldendTime;

    public void setEndTime(Timestamp timestamp)
    {
        endTime = timestamp;
    }

    public Timestamp getEndTime()
    {
        return endTime;
    }

    public Timestamp getoldEndTime()
    {
        return oldendTime;
    }

    public void setoldEndTime(Timestamp timestamp)
    {
        oldendTime = timestamp;
    }
    
    private String futureSchedulingOnly;
    private String oldfutureSchedulingOnly;

    public String getFutureSchedulingOnly()
    {
        return futureSchedulingOnly;
    }

    public String getoldFutureSchedulingOnly()
    {
        return oldfutureSchedulingOnly;
    }

    public void setFutureSchedulingOnly(String string)
    {
        if (string == null || string.equals(""))
        {
            string = "Y";
        }
        futureSchedulingOnly = string;
    }

    public void setoldFutureSchedulingOnly(String string)
    {
        if (string == null || string.equals(""))
        {
            string = "Y";
        }
        oldfutureSchedulingOnly = string;
    }
    
    private String fixedDate;
    private String oldfixedDate;
    
    public void setFixedDate(String strFixedDate) {
    	if (strFixedDate == null || strFixedDate.equals("")) {
    		strFixedDate = "N";
    	} else if ("YN".indexOf(strFixedDate) < 0) {
            throw new IllegalArgumentException("Fixed Date can be either Y or N");
        }
    	fixedDate = strFixedDate;
    }

    public void setoldFixedDate(String strFixedDate) {
        if (strFixedDate == null || strFixedDate.equals("")) {
            strFixedDate = "N";
        } else if ("YN".indexOf(strFixedDate) < 0) {
            throw new IllegalArgumentException("Fixed Date can be either Y or N");
        }
    	oldfixedDate = strFixedDate;
    }
    
    public String getFixedDate() {
        if (fixedDate == null || fixedDate.equals("")) {
            return "N";
        } else if ("NY".indexOf(fixedDate) < 0) {
            return "N";
        }
    	return fixedDate;
    }
    
    public String getoldFixedDate() {
        if (oldfixedDate == null || oldfixedDate.equals("")) {
            return "N";
        } else if ("NY".indexOf(oldfixedDate) < 0) {
            return "N";
        }
        return oldfixedDate;
    }
    

    private void checkNull( String pstrMessage, Object obj ) throws CBeanException{
        if ( obj == null ) throw new CBeanException( pstrMessage + " : Mandatory Field. Cannot Be Left Blank." );
        if ( obj.equals("") ) throw new CBeanException( pstrMessage + " : Mandatory Field. Cannot Be Left Blank." );
    }


    public void checkMandatory() throws CBeanException{
        checkNull( "freqType", freqType );
        checkNull( "startDt", startDt );
        checkNull( "schStat", schStat );
        checkNull( "userId", userId );
        checkNull( "fixedDate", fixedDate);
    }


    public void initialize() {
        schId = 0;
        oldschId = 0;
        freqType = null;
        oldfreqType = null;
        recur = 0;
        oldrecur = 0;
        startDt = null;
        oldstartDt = null;
        schStat = null;
        oldschStat = null;
        userId = null;
        olduserId = null;
        onWeekDay = null;
        oldonWeekDay = null;
        endDt = null;
        oldendDt = null;
        endOccur = 0;
        oldendOccur = 0;
        entryDt = null;
        oldentryDt = null;
        modifyId = null;
        oldmodifyId = null;
        modifyDt = null;
        oldmodifyDt = null;
        reqStat = null;
        oldreqStat = null;
        rStatus = false;
        processClassNm = null;
        oldprocessClassNm = null;
        startTime = null;
        oldstartTime = null;
        endTime = null;
        oldendTime = null;
        futureSchedulingOnly = null;
        oldfutureSchedulingOnly = null;
        fixedDate = null;
        oldfixedDate = null;
        emailIds = "";
        oldemailIds = "";
        skipFlag = "";
        oldskipFlag = "";
        weekdayCheckFlag = "";
        oldweekdayCheckFlag = "";
        endReason = "";
        oldendReason = "";
        keepAlive = "N";
        oldkeepAlive = "N";
    }


    public void setRStatus(boolean b){
        this.rStatus = b;
    }
    public boolean getRStatus(){
        return rStatus;
    }


    public Object clone()
    {
        try
        {
            return super.clone();
        }
        catch(CloneNotSupportedException cnse)
        {
            return null;
        }
    }


    public String toString()
    {
        return "SCH_ID=" + schId;
    }

    boolean rStatus = false;

    private String emailIds = "";
    private String oldemailIds = "";
    
    public void setEmailIds(String pemailIds) {
        if (pemailIds == null) {
            this.emailIds = "";
        } else {
            this.emailIds = pemailIds;
        }
    }

    public void setoldEmailIds(String poldemailIds) {
        if (oldemailIds == null) {
            this.oldemailIds = "";
        } else {
            this.oldemailIds = poldemailIds;
        }
    }
    
    public String getEmailIds() {
        return this.emailIds;
    }
    
    public String getoldEmailIds() {
        return this.oldemailIds;
    }

    private String skipFlag = "";
    private String oldskipFlag = "";
    
    public void setSkipFlag(String skipFlag) {
        this.skipFlag = skipFlag; 
    }

    public void setoldSkipFlag(String oldskipFlag) {
        this.oldskipFlag = oldskipFlag; 
    }
    
    public String getSkipFlag() {
        return this.skipFlag;
    }
    
    public String getoldSkipFlag() {
        return this.oldskipFlag;
    }
    
    private String weekdayCheckFlag = "";
    private String oldweekdayCheckFlag = "";
    
    public void setWeekdayCheckFlag(String weekdayCheckFlag) {
        this.weekdayCheckFlag = weekdayCheckFlag;
    }
    
    public void setoldWeekdayCheckFlag(String oldweekdayCheckFlag) {
        this.oldweekdayCheckFlag = oldweekdayCheckFlag;
    }
    
    public String getWeekdayCheckFlag() {
        return this.weekdayCheckFlag;
    }
    
    public String getoldWeekdayCheckFlag() {
        return this.oldweekdayCheckFlag;
    }
    
    private String endReason;
    private String oldendReason;
    
    /**
	 * @param endReason the endReason to set
	 */
	public void setEndReason(String endReason) {
		this.endReason = endReason;
	}

	/**
	 * @return the endReason
	 */
	public String getEndReason() {
		return endReason;
	}

	/**
	 * @param endReason the endReason to set
	 */
	public void setoldEndReason(String endReason) {
		this.oldendReason = endReason;
	}
	
	/**
	 * @return the endReason
	 */
	public String getoldEndReason() {
		return oldendReason;
	}

	private String keepAlive;
	private String oldkeepAlive;
	
	/**
	 * @param keepAlive the keepAlive to set
	 */
	public void setKeepAlive(String keepAlive) {
		this.keepAlive = keepAlive;
	}

	/**
	 * @return the keepAlive
	 */
	public String getKeepAlive() {
		return keepAlive;
	}

	
	/**
	 * @param oldkeepAlive
	 */
	public void setoldKeepAlive(String oldkeepAlive) {
		this.oldkeepAlive = oldkeepAlive;
	}
	
	/**
	 * Returns the oldkeepAlive
	 * @return oldkeepAlive
	 */
	public String getoldKeepAlive() {
		return oldkeepAlive;
	}
	

	
}
