/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */
package com.stgmastek.monitor.ws.util;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

import javax.mail.MessagingException;
import javax.mail.Part;
import javax.mail.util.ByteArrayDataSource;

import com.stgmastek.monitor.mailer.EMailAttachment;

/**
 * @author Lakshman Pendrum
 *
 */
public abstract class BaseEmail {

	private EMailAttachment image = null;
	
	/**
	 * Method to create the content when the batch starts
	 * 
	 * @return the content of the email as string
	 */
	public String getDefaultStyleSheet() {
		StringBuilder sb = new StringBuilder();
		sb.append("    <style type='text/css'> ");
		sb.append("    .blockHeader{ ");
		sb.append("        FONT-WEIGHT: bold; ");
		sb.append("        FONT-SIZE: 10pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("    }  ");
		sb.append("    .trHeader{ ");
		sb.append("        FONT-WEIGHT: bold; ");
		sb.append("        FONT-SIZE: 8pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("        border: inset 1pt; ");
		sb.append("        background-color: #b3b3b3; ");
		sb.append("    } ");
		sb.append("    .trRow1{ ");
		sb.append("        FONT-SIZE: 8pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("        border: inset 1pt; ");
		sb.append("        background-color: #F0F0F0; ");
		sb.append("    }	");
		sb.append("    .trRow2{ ");
		sb.append("        FONT-SIZE: 8pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("        border: inset 1pt; ");
		sb.append("        background-color: #F7F7F7; ");
		sb.append("    }	");
		sb.append("    .trHeaderFooter{ ");
		sb.append("        FONT-SIZE: 8pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("        border: outset 2pt; ");
		sb.append("        background-color: #F7F7F7; ");
		sb.append("        border-color:#00a6d6; ");
		sb.append("    }	");
		sb.append("    .plainText{ ");
		sb.append("        FONT-SIZE: 8pt; ");
		sb.append("        COLOR: #333399; ");
		sb.append("        FONT-FAMILY: Arial,Helvetica,Sans-serif; ");
		sb.append("        TEXT-DECORATION: none; ");
		sb.append("        background-color: while; ");
		sb.append("    }	");
		sb.append("    .dTable{ ");
		sb.append("      border: 1px solid #aa9; ");
		sb.append("      border-color:#333399; ");
		sb.append("    } ");
		sb.append("    body{ ");
		sb.append("      background-color: white; ");
		sb.append("    } ");
		sb.append("    </style> ");
		return sb.toString();
	}

	/**
	 * TODO: Add javadoc
	 * @return html email header as String
	 */
	public String getDefaultHeader() {
		StringBuilder sb = new StringBuilder();
		sb.append("<TABLE width='100%'>");
		sb
				.append("<TR><TD class=\"trHeaderFooter\"><img alt=\"jbeam.gif\" src=\"jbeam.gif\">This message is automatically generated by the Java Batch Execution And Monitoring system. Please do not reply. Contact your help desk or on-site support if you need any assistance.</TD></TR></TABLE> ");
		return sb.toString();
	}

	/**
	 * TODO: Add Java doc
	 * @return html email footer as String
	 */
	public String getDefaultFooter() {
		StringBuilder sb = new StringBuilder();
		sb
				.append("<TABLE width='100%'><TR><TD class=\"trHeaderFooter\"><b>DISCLAIMER</b>: Information contained and transmitted by this E-MAIL is proprietary to the Java Batch Execution And Monitoring system. This is an auto generated mail intended only for certain privileged users of the system.Access to this email by anyone else is unauthorized. Any copying or further distribution beyond the original addressee is not intended.</TD></TR></TABLE> ");
		return sb.toString();

	}
	
	/**
	 * Method to create the content email content
	 * 
	 * @return the content of the email as string
	 */
	public String getEmailContent() {
		StringBuilder sb = new StringBuilder();
		sb.append("  <HTML> ");
		sb.append("  <HEAD> ");
		sb.append("  <TITLE></TITLE> ");
		sb.append(getDefaultStyleSheet());
		sb.append("  </HEAD> ");
		sb.append("  <BODY> ");
		sb.append(getDefaultHeader());
		sb.append(getHTMLEmailContent());
		sb.append(getDefaultFooter());
		sb.append("  </BODY> ");
		sb.append("  </HTML> ");

		return sb.toString();
	}

    /**
     * Returns the input stream for the given resource.
     * 
     * @param clazz
     * @param path
     * @return InputStream
     * @throws IOException
     */
    private InputStream getResourceInputStream(Class<?> clazz, String path) throws IOException {
        InputStream is = null;
        if ( clazz != null ) {
            is = clazz.getResourceAsStream( path );
        }
        
        if ( is == null ) {
        	is = this.getClass().getClassLoader().getResourceAsStream( path );
        }

        if ( is == null ) {
            is = Thread.currentThread().getContextClassLoader().getResourceAsStream( path );
        }

        if ( is == null ) {
            is = ClassLoader.getSystemClassLoader().getResourceAsStream( path );
        }

        if ( is == null ) {
            throw new FileNotFoundException( "'" + path + "' cannot be opened because it does not exist" );
        }
        return is;
    }	
	
    /**
     * Returns the JBeam Logo as an email attachment.
     * 
     * @return EMailAttachment
     * @throws IOException
     */
    public EMailAttachment getJbeamLogo() throws IOException {
		if (image == null) {
			InputStream is = null;
			try {
				is = getResourceInputStream(this.getClass(), "resources/jbeam.gif");
				
			} catch (IOException e) {
			}
			if (is != null) {
				image = new EMailAttachment("jbeam.gif",
						new ByteArrayDataSource( is, 
								"image/gif"));
				image.setDisposition(Part.INLINE);
			}
		}
		return image;
    }
    
    /**
	 * Method for the sub classes to implement and send an email
	 * 
	 */
    public abstract void sendEmail()  throws IOException, MessagingException;
    
    /**
	 * Method for the sub classes to implement and create the HTML content to be shown in email
	 * 
	 */
    public abstract String getHTMLEmailContent();
    
}

/*
* Revision Log
* -------------------------------
* $Log:: /Product_Base/Projects/Batch/Code/Java/MonitorServices/src/com/stgmastek/monitor/mailer/UserAccountEMail.java                                                               $
 * 
*
*/