/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */
package com.stgmastek.monitor.ws.util;

/**
 * @author yogesh.j
 * 
 */
public interface IExceptionConstants {

	public interface Business {

		// Exception message range : (201 and above)

		String LOGIC_FAILED = "RBS-201";  
		String INVALID_USER_ID = "RBS-202";
		String INVALID_PASSWORD = "RBS-204";
		String UPDATE_SECURITY_QUESTIONS_FAILURE = "RBS-203";
		String INVALID_EMAIL_ID = "RBS-205";// added for my profile
		String UPDATE_EMAIL_ID_FAILURE = "RBS-206";// added for my profile
		String UPDATE_PASSWORD_FAILURE = "RBS-207";
		String USER_ID_NULL = "RBS-208";
		String NEWPASS_CONFIRMPASS_NOTMATCH = "RBS-209";
		String ANET_CONNECTION_ERROR = "RBS-210";
		String INSTRUMENT_DETAILS_NOT_FOUND = "RBS-211";
		String PAYMENT_GATEWAY_RESPONSE_NOT_FOUND = "RBS-212";
		String ANETGATEWAY_RESPONSE_NOT_FOUND = "RBS-213";
		String ENTITY_DETAILS_NOT_FOUND = "RBS-214";
		String PAYMENT_SCHEDULE_NOT_FOUND = "RBS-215";
		String ANET_DATA_NOT_FOUND = "RBS-216";
		String USER_CREDENTIAL_NOT_FOUND = "RBS-217";
		String USER_NOT_EXISTS = "RBS-218";
		String USER_SUSPENDED = "RBS-219";
		String USER_DELETED = "RBS-220";
		String NO_EMAIL_TEMPLATE_FOUND = "RBS-221";
		String INVALID_EMAIL_TEMPLATE = "RBS-222";
		String ALL_QUESTIONS_NOT_ANSWERED = "RBS-223";
		String INCORRECT_ANSWERS = "RBS-224";
		String ACCOUNT_NAME_NOT_FOUND = "RBS-225";
		String POLICY_BALANCE_NOT_FOUND = "RBS-226";
		String POLICY_DATES_NOT_FOUND = "RBS-227";
		String POLICY_NAME_NOT_FOUND = "RBS-228";
		String ACCOUNT_BALANCE_NOT_FOUND = "RBS-229";
		String ACCOUNT_DATES_NOT_FOUND = "RBS-230";
		String NO_ZIPCODE = "RBS-231";
		String INVALID_ZIPCODE = "RBS-232";
		String NO_DUE_AMOUNT = "RBS-233";
		String INVALID_DUE_AMOUNT = "RBS-234";
		String NO_TOTAL_PREMIUM = "RBS-235";
		String INVALID_TOTAL_PREMIUM = "RBS-236";
		String NO_USER_DETAILS = "RBS-237";
		String NO_REGISTRATION_DETAILS = "RBS-238";
		String NO_ENTITY_DETAILS = "RBS-239";
		String NO_QUESTION_ID = "RBS-240";
		String INVALID_QUESTION_ID = "RBS-241";
		String NO_AMOUNT = "RBS-242";
		String INVALID_AMOUNT = "RBS-243";
		String NO_ENTITY_TYPE = "RBS-244";
		String INVALID_ENTITY_TYPE = "RBS-245";
		String ACCOUNT_PRESENT = "RBS-246";
		String POLICY_PRESENT = "RBS-247";
		String NO_ENTITY_CODE = "RBS-248";
		String INVALID_ENTITY_CODE = "RBS-249";
		String NO_QUESTION_CATEGORY = "RBS-250";
		String NO_QUESTIONS = "RBS-251";
		String NO_SECURITY_QUESTIONS = "RBS-252";
		String INVALID_SECURITY_QUESTION = "RBS-253";
		String INVALID_SECURITY_ANSWER = "RBS-254";
		String DUPLICATE_QUESTIONS = "RBS-255";
		String NO_USER_NAME = "RBS-256";
		String INVALID_USER_NAME = "RBS-257";
		String NO_PASSWORD = "RBS-258";
		String NO_EMAIL = "RBS-259";
		String INVALID_EMAIL = "RBS-260";
		String INVALID_RENEW_NUMBER = "RBS-261";
		String NO_TELEPHONE_NUMBER = "RBS-262";
		String INVALID_TELEPHONE_NUMBER = "RBS-263";
		String VERIFICATION_CRITERIA_UNSATISFIED = "RBS-264";
		String USER_ID_ALREADY_EXISTS = "RBS-265";
		String ACCOUNT_DELETED = "RBS-266";
		String ACCOUNT_SUSPENDED = "RBS-267";
		String CHANGE_PASSWORD = "RBS-268";
		String PASSWORD_EXPIRED = "RBS-269";
		String INVALID_PASSWORD_ACCOUNT_SUSPENDED = "RBS-270";
		String INVALID_CREDENTIALS = "RBS-271";
		String PASSWORD_NULL = "RBS-272";
		String INVALID_ACCOUNT = "RBS-273";

		String PAYMENT_INSTRUMENT_NOT_FOUND = "RBS-275";
		String NO_SECURITY_ANSWER = "RBS-276";
		String NEGATIVE_TOTAL_PREMIUM_FOR_ACCOUNT = "RBS-277";
		String NON_MATCHING_TOTAL_PREMIUM_FOR_ACCOUNT = "RBS-278";
		String NEGATIVE_TOTAL_PREMIUM_FOR_POLICY = "RBS-279";
		String NON_MATCHING_TOTAL_PREMIUM_FOR_POLICY = "RBS-280";
		String INVALID_DUE_AMOUNT_FOR_POLICY = "RBS-281";
		String NEGATIVE_DUE_AMOUNT_FOR_POLICY = "RBS-282";
		String NON_MATCHING_DUE_AMOUNT_FOR_POLICY = "RBS-283";
		String INVALID_DUE_AMOUNT_FOR_ACCOUNT = "RBS-284";
		String NEGATIVE_DUE_AMOUNT_FOR_ACCOUNT = "RBS-285";
		String NON_MATCHING_DUE_AMOUNT_FOR_ACCOUNT = "RBS-286";
		String NO_SUCH_ACCOUNT = "RBS-287";
		String NO_SUCH_POLICY = "RBS-288";
		String NO_SUCH_POLICY_WITHOUT_RENEW = "RBS-314";
		String NOT_SINGLE_BILLED = "RBS-289";
		String UNABLE_TO_OPEN_PDF = "RBS-290";
		String CHANGE_PASSWORD_WARNING_MSG = "RBS-291";
		String CHANGE_PASSWORD_MSG = "RBS-292";
		String DEPARTMENT_NOT_FOUND = "RBS-293";
		String MENU_DETAILS_NOT_FOUND = "RBS-294";
		String ACCOUNT_DETAILS_NOT_FOUND = "RBS-295";
		String POLICY_DETAILS_NOT_FOUND = "RBS-296";
		String CIM_CREATE_CUSTOMER_PROFILE_RESPONSE_NOT_FOUND = "RBS-297";
		String CIM_PROFILE_NOT_FOUND = "RBS-298";
		String CIM_NO_PAYMENT_PROFILES_EXIST = "RBS-299";
		String CIM_SPECIFY_PAYMENT_PROFILE = "RBS-300";
		String NO_REGISTERED_SECURITY_QUESTIONS_FOUND = "RBS-301";
		String NO_REGISTERED_SECURITY_QUESTIONS_CONFIGURED = "RBS-302";
		String CIM_CREATE_CUSTOMER_PAYMENT_PROFILE_RESPONSE_NOT_FOUND = "RBS-303";
		String CIM_CUSTOMER_PROFILE_DETAILS_NOT_FOUND = "RBS-304";
		String INSTRUMENT_NAME_NOT_FOUND = "RBS-305";
		String INSTRUMENT_NAME_EXISTS = "RBS-306";
		String NO_RENEW_NUMBER = "RBS-307";
		String ACCOUNT_INSURED_NAME_NULL = "RBS-308";
		String POLICY_INSURED_NAME_NULL = "RBS-309";
		String INVALID_SESSION = "RBS-310";

		String POLICY_STATUS_NOT_FOUND = "RBS-311";
		String HOLDSUSPEND_DETAILS_NOT_FOUND = "RBS-321";
		String ENTITY_DETAILS_NOT_FOUND_FOR_POLICY = "RBS-314";
		String BILLING_DETAILS_NOT_FOUND = "df";
		String TRANSACTION_DETAILS_NOT_FOUND = "RBS-312";
		String CASH_APPLIED_DETAILS_NOT_FOUND = "RBS-313";
		String DUMMY_BATCH_ERROR = "RBS-318";
		String MANUAL_ALLOCATION_ERROR = "RBS-319";
		String INSERT_CASHBATCH_ERROR = "RBS-321";
		String BATCH_TOTAL_ERROR = "RBS-322";
		String INSERTION_ERROR = "RBS-323";
		String MODIFICATION_ERROR = "RBS-324";
		String DROPDOWN_MASTER_CODE_ERROR = "RBS-329";
		String INVALID_SEARCH_OPTION = "RBS-330"; 
		String NO_RECORDS_FOUND="RBS-331";
		String INVALID_COMM_LIABILITY_ERROR="RBS-332";
		String INVALID_CASH_BATCH_DETAILS_ERROR="RBS-333";
		String DROPDOWN_ALLOCATED_LIST_ERROR = "RBS-334";
		String INVALID_AUTO_ALLOCATE_ERROR = "RBS-335";
		String CASH_TRANSACTION_ERROR = "RBS-336";
		String SAN_NOT_GENERATED = "RBS-337";
		String BEGIN_IO_ERROR = "RBS-338";
		String CASHBATCH_DETAILS_NOT_FOUND = "RBS-339";
		
		String INVALID_ACCOUTING_YEAR_MONTH = "RBS-340";
		String CLOSING_BATCH_NO_CHECKS_NOT_MATCHED = "RBS-341";
		String INVALID_BATCH_AMOUNT = "RBS-342";
		String CLOSING_BATCH_TOTAL_NOT_MATCHED = "RBS-343";
		String EMPTY_BATCH = "RBS-344";
		String INVALID_DEPOSIT_DATE = "RBS-345";
		String DEPOSIT_DATE_LESS_THAN_SYSDATE = "RBS-346";
		String INVALID_BANK = "RBS-347";
		String ACCOUTING_YEAR_MONTH_ALREADY_CLOSED = "RBS-348";
		String ASSIGNED_CHECK_DETAILS_ERROR = "RBS-350";
		String INVALID_GL_ACCOUNT_EXPENSES_ALLOCATION_DETAILS = "RBS-351";
		String INVALID_PROCESS_GL_ALLOCATION = "RBS-353";
		String REASSIGN_AGENNCY_CASH_ALLOCATION_INSERT_ERROR = "RBS-353";
		String INVALID_ALLOCATE_ERROR = "RBS-357";
		String INVALID_OTHER_BILL_POLICY_CHECK_ERROR = "RBS-358";
		String INVALID_POLICY = "RBS-274";
		String CASHBATCH_DATA_MISMATCH = "RBS-360";
		String CASHBATCH_RETRIEVAL_EXCEPTION = "RBS-361";
		String CASH_NUMBER_NOT_GENERATED = "RBS-362";
		String END_IO_ERROR = "RBS-363";
		String INVALID_OTHER_BILL_ACCOUNT_CHECK_ERROR = "RBS-364"; 
		String CASH_ALLOCATION_DETAILS_INSERTION_ERROR = "RBS-365";
		String ASSIGNED_CHECK_TRANSACTON_DETAILS_ERROR = "RBS-366";
		String CLOSE_CASHBATCH_ERROR = "RBS-367";
		//String GET_SYSTEM_ACTIVITY_CODE_ERROR = "RBS-368";
		String INVALID_OTHER_BILL_ACCOUNT_TRANSACTION_ERROR = "RBS-369";
		String DISCARD_MANUAL_CASH_ALLOCATION_ERROR = "RBS-370";
		String DELETE_OPEN_CASHBATCH_CHECK_ERROR = "RBS-371";
		String INVALID_OTHER_BILL_POLICY_TRANSACTION_ERROR = "RBS-372";
		String CHECK_SEARCH_RESULT_ERROR = "RBS-373";
		String INVALID_CASH_ALLOCATION_LOAD_ERROR = "RBS-374";
		String INVALID_OVER_CASH_ALLOCATION_ERROR = "RBS-375";
		String DELETE_CASH_ALLOCATE_ERROR = "RBS-376";
		String INVALID_PAYMENT_FROM_ERROR = "RBS-377";
		String NO_VALID_POLICY_EXIST_ON_ACCOUNT = "RBS-378";
		String INVALID_ACCOUNT_NO = "RBS-379";
		
		String INVALID_CHECK_AMOUNT_ERROR = "RBS-380";
		String CASH_TYPE_NOT_PREMIUM_ERROR = "RBS-381";
		String ENTER_VALID_ENTITY_ERROR = "RBS-382";
		
		String SYSATEM_ACTIVITY_NUMBER_GENERATION_ERROR = "RBS-383";
		String INVALID_CASHBATCH_DETAILS_ERROR = "RBS-384";
		String INVALID_POLICY_NO = "RBS-385";
		String INVALID_POLICY_FOR_MANUAL_ALLOCATION = "RBS-386";
		String INVALID_ACCOUNT_FOR_MANUAL_ALLOCATION = "RBS-387"; 
		String USER_CONTEXT_ERROR = "RBS-388";
		String DEPARTMENT_ERROR = "RBS-389";
		String VALIDATE_REFERENCE_ID = "RBS-394";
		
		String CASH_DETAILS_RESULT_ERROR = "RBS-390";
		String CHECK_DETAILS_RESULT_ERROR = "RBS-391";
		String NSF_FEE_LEVEL_ERROR = "RBS-392";
		String POLICY_DUES_FOR_BATCH_ERROR = "RBS-393";  
		String DEPARTMENT_NAME_NOT_FOUND = "RBS-395";
		
		String NSF_LEVEL_RESULT_ERROR = "RBS-396";
		String NSF_PROCESS_RESULT_ERROR = "RBS-397"; 
		String NOTEPAD_DETAILS_NOT_FOUND = "RBS-398";
		String NOTES_NOT_FOUND = "RBS-399";
		String PDF_FOUND = "RBS-400";
		
		String NO_MORTGAGEE_ON_THE_POLICY = "RBS-401";
		String INVALID_PAYMENT_FROM = "RBS-402";
		String INVALID_APPLIED_TO_DETAILS = "RBS-403";
		String NO_RECORD_FOUND_FOR_POLICY = "RBS-404";
		String NO_RECORD_FOUND_FOR_ACCOUNT = "RBS-405";
		String INVALID_AGENCY_CODE = "RBS-406";
		String HOLD_SUSPEND_ERROR = "RBS-407";
		String HOLD_SUSPEND_INSERT_ERROR = "RBS-408";
		String TRANSACTION_SUCCESSFUL = "RBS-409";
		String NSF_DSF_FEES_ERROR = "RBS-410";
		String ACCOUNT_TRANSACTION_SUCCESSFUL_RELEASED = "RBS-411";
		String SUSPEND_HOLD_STATUS_NOT_FOUND = "RBS-412";
		String SUSPEND_HOLD_CODE_NOT_FOUND = "RBS-413";
		String RELEASE_DATE_NOT_FOUND = "RBS-414";
		String OPERATE_ON_NOT_FOUND = "RBS-416";
		String NOC_SUSPEND_REASON_NOT_FOUND = "RBS-417";
		String NOC_REASON_DATE_NOT_FOUND = "RBS-418";
		String ACCOUNT_BILL_POLICY_ERROR = "RBS-419";
		String SUSPEND_HOLD_DETAILS_NOT_FOUND = "RBS-420";
		String INSTALLMENT_SCHEDULE_POPULATION_ERROR = "RBS-421";
		String MAX_WRITE_OFF_ERROR = "RBS-422";
		String INSERT_WRITE_OFF_DUES_ERROR = "RBS-423";
		String INSERT_NEW_INSTALLMENT_SCHEDULE_ERROR = "RBS-424";
		String NEW_IS_DATE_NOT_FOUND = "RBS-425";
		String INVALID_NEW_SEND_DATE = "RBS-426";
		String INVALID_SEND_DATE = "RBS-427";
		String BILL_LEAD_TIME_ERROR = "RBS-428";
		String COMMUNICATION_MESSAGES_ERROR = "RBS-429";
		String POLICY_AUDIT_ERROR = "RBS-430";
		String LOV_RECORD_INSERT_ERROR = "RBS-431";
		String LOV_RECORD_DELETE_ERROR = "RBS-432";
		String LOV_RECORD_UPDATE_ERROR = "RBS-433";
		String ACCOUNT_NOT_HOLD = "RBS-434";
		String LOV_MASTER_CODE_MISSING = "RBS-435";
		String MANUAL_REFUND_PAYEE_DETAILS_ERROR = "RBS-436";
		
		String COMMISSION_ADJUSTMENT_ERROR = "RBS-437";
		String INVALID_AGENT_DETAILS = "RBS-438";
		String PREMIUM_AMOUNT_IS_BLANK = "RBS-439";
		String POLICY_EFFECIVE_DATE_IS_BLANK = "RBS-440";
		String ADJUSTMENT_AMOUINT_IS_BLANK = "RBS-441";
		String INVALID_AGENT = "RBS-442";
		String AGENT_IS_BLANK = "RBS-443";
		String BATCH_NO_DETAILS_RESULT_ERROR = "RBS-444";
		String INVALID_VIEW_COMMISSION_ADJUSTMENT_FILTER = "RBS-445";
		String MANUAL_REFUND_ACCOUNT_DETAILS_RESULT_ERROR = "RBS-446";
		String MANUAL_REFUND_TRANSACTION_DETAILS_RESULT_ERROR = "RBS-447";
		String MANUAL_REFUND_POLICY_DETAILS_RESULT_ERROR = "RBS-448";
		String MANUAL_REFUND_AUTO_ALLOCATION_RESULT_ERROR = "RBS-449";
		String INVALID_INPUT_DETAILS = "RBS-450"; 
		String RETRIEVE_ERROR = "RBS-451";
		String MANUAL_REFUND_DETAILS_INSERTION_ERROR = "RBS-452";
		
		String COMMISSION_INSERT_AGENT_ERROR = "RBS-453";
		String COMMISSION_INSERT_SPECIFIC_AGENT_ERROR = "RBS-454";
		String SUBMIT_COMMISSION_EXTRACTION_DETAILS_ERROR = "RBS-455";
		String MANUAL_REFUND_MASTER_INSERTION_ERROR = "RBS-456";
		
		String COMMISSION_EXTRACTION_BATCH_ALREADY_EXIST = "RBS-457";
		String FEES_DISBURSEMENT_STATUS_ERROR_MESSAGE = "RBS-458";
		String PREMIUM_DISBURSEMENT_STATUS_ERROR_MESSAGE = "RBS-459";
		
		String PARAMETER_MASTER_INSERT_ERROR = "RBS-460";
		String PARAMETER_MASTER_UPDATE_ERROR = "RBS-461";
		String PARAMETER_MASTER_DELETE_ERROR = "RBS-462";
		
		String COMMISSION_ACCOUNTING_YEAR_MONTH_NOT_FOUND = "RBS-463";
		String COMMISSION_EXTRACTION_TYPE_NOT_FOUND = "RBS-464";
		String COMMISSION_BROKER_CODE_NOT_FOUND = "RBS-465";
		String COMMISSION_BATCH_NO_NOT_FOUND = "RBS-466";
		String USER_ID_NOT_FOUND = "RBS-467";
		
		String COMMISSION_SUSPEND_ERROR = "RBS-468";
		String COMMISSION_RELEASE_ERROR = "RBS-469";
		
		String COMMISSION_EXTRACTION_BATCH_ALREADY_CLOSED = "RBS-470";
		String COUNTERSIGN_FEE_DISBURSEMENT_BATCH_ALREADY_CLOSED = "RBS-471";
		String REFUND_PREMIUM_DISBURSEMENT_BATCH_ALREADY_CLOSED = "RBS-472";
		
		String RETRIEVE_POLICY_ENTITY_DETAILS_ERROR = "RBS-473";
		String COMMISSION_BATCH_CLOSURE_ERROR = "RBS-474";
		
		String INSERT_MANUAL_BILL_ENTRY_ERROR = "RBS-475";
		String NO_COMMISSION_BATCH_EXIST_FOR_REVIEW = "RBS-476";
		
		String PROC_EXECUTION_FAILED_EXCEPTION = "RBS-477";		
		String INSERT_ENTITY_INTERFACE_ERROR = "RBS-478";
		String ADDRESS_NOT_FOUND = "RBS-479";
		String CITY_NOT_FOUND = "RBS-480";
		String STATE_NOT_FOUND = "RBS-481";
		String ZIP_CODE_NOT_FOUND = "RBS-482";
		
		String TRANSACTION_TYPE_NOT_FOUND = "RBS-483"; 
		String TRANSACTION_FOR_POLICY_SUCCESSFUL = "RBS-484";
		
		String AGENT_POLICY_COMBINATION_NOT_EXIST  = "RBS-485";
		String POLICY_TRANSACTION_SUCCESSFUL_RELEASED = "RBS-486";
		
		String PENDING_PAY_FILE_UPDATE_ERROR = "RBS-487";
		
		String DELETE_BATCH_ERROR = "RBS-488";
		String DELETE_BATCH_SUCCESS = "RBS-489";
		String COMMUNICATION_DETAILS_NOT_FORUND = "RBS-490";
		String CONTEXT_REFERENCEID_NOT_FORUND = "RBS-491";
		String CONTEXT_NOT_FORUND = "RBS-492";
		String REFERENCEID_NOT_FORUND = "RBS-493";
		String PRIORITY_NOT_FORUND = "RBS-494";
		String SUBJECT_NOT_FORUND = "RBS-495";
		String COMMUNICATIONTEXT_NOT_FORUND = "RBS-496";
		String FROMDATE_NOT_FORUND = "RBS-497";
		String ATTENTION_USER_DEPT__NOT_FORUND = "RBS-498";
		String INVALID_FROMDATE = "RBS-499";
		String ATTENTION_USER_NOT_FORUND = "RBS-500";
		String ATTENTION_DEPT_NOT_FORUND = "RBS-501";
		String DIARY_MANDETORY_FIELDS = "RBS-502";
		String DIARY_TO_DATE = "RBS-503";
		String DIARY_FROM_DATE = "RBS-504";
		String DIARY_CONTEXT = "RBS-505";
		String DIARY_REFERENCE_ID = "RBS-506";
		String DIARY_COMMUNICATION_DETAILS = "RBS-507";
		String ACTION_NOT_FORUND = "RBS-508";
		String MAX_LENGTH_EXCEED = "RBS-509";
		String REASSIGN_PRODUCER_SUCCESS = "RBS-510";
		String INVALID_UNDELETE = "RBS-517";

		String LOV_RECORD_EXISTS_ERROR = "RBS-518";
		
		String SAVE_DATAGRID_PREFERENCE_SUCCESS = "RBS-519";
		
		String CANCELLATION_PREVIEW_SEARCH_RESULT_ERROR = "RBS-520";
		String CANCELLATION_PREVIEW_ERROR = "RBS-521";
		String CANCELLATION_REVIEW_SUCESS = "RBS-522";
		String UPDATE_REMARKS_CANCEL_PREVIEW_POLICIES_ERROR = "RBS-523";
		String UPDATE_REMARKS_CANCEL_PREVIEW_POLICIES_SUCESS = "RBS-524";
		String PROCESS_SUSPEND_TRAN_SUCCESS = "RBS-525";
		String SUSPEND_RELEASE_NOC_ZIPCODE_SEARCH_RESULT_ERROR = "RBS-526";
		String SUSPEND_RELEASE_NOC_POLICIES_SEARCH_RESULT_ERROR = "RBS-527";
		String SUSPEND_NOC_PROCESS_ERROR = "RBS-528";
		String PROCESS_SUSPEND_NOC_NO_RECORDS_ERROR = "RBS-529";
		String RELEASE_NOC_PROCESS_ERROR = "RBS-530";
		String SUSPEND_NOC_PROCESS_SUCCESS = "RBS-531";
		String PROCESS_RELEASE_TRAN_SUCCESS = "RBS-532";
		String REPORT_PARAMETER_ERROR = "RBS-533";
		String INSERT_REPORT_DATA_ERROR = "RBS-534";
		String INSUFFICIENT_USER_RIGHTS_ERROR = "RBS-535";
		String DELETE_FAILED_TRANSACTIONS_ERROR = "RBS-536";
		String REPORT_NAME_ERROR = "RBS-537";
		String PROCESS_REQUEST_SUCCESS = "RBS-538";
		String SCHEDULE_REPORT_ERROR = "RBS-539";
		String EXCEL_PATH_ERROR = "RBS-540";
		String REPORT_MASTER_ERROR = "RBS-541";
		String QUERY_FIELDS_ERROR = "RBS-542";
		String REPORT_HEADING_ERROR = "RBS-543";
		String PROCESS_FAILED_TRANSACTIONS_SUCCESS ="RBS-544";
		String UPDATE_SCHEDULE_STATUS_FAILURE ="RBS-545";
		String UPDATE_SCHEDULE_STATUS_SUCCESS ="RBS-546";
		String UPDATE_REQUEST_STATUS_FAILURE ="RBS-547";
		String UPDATE_REQUEST_STATUS_SUCCESS ="RBS-548";


	}

	public interface Data {

		// Exception code range : (101 to 200)

		String UNKNOWN_DATA = "RBS-101";
		String ANET_DATA_NOT_FOUND = "RBS-102";

		String PROCESS_LOCKBOX_BATCH_HEADER_RECORD = "RBS-104";
		String PROCESS_LOCKBOX_BATCH_DETAILS_RECORD = "RBS-105";
		String PROCESS_LOCKBOX = "RBS-106";
		String PROCESS_LOCKBOX_HEADER = "RBS-107";
		String NO_DATA_FOUND = "RBS-108";
		String INVALID_USER_NAME = "RBS-109";
		String IN_VALID_DIARY = "RBS-110";

	}

	public interface Unknown {
		// Exception code range : (001 to 100)
		String UNKNOWN_ERROR = "RBS-001";
	}

}
