/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */
package com.stgmastek.core.comm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Jan 28 16:40:36 IST 2013
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://services.server.comm.core.stgmastek.com/", name = "CoreCommServices")
@XmlSeeAlso({ObjectFactory.class})
public interface CoreCommServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProcessReqSchedule", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.GetProcessReqSchedule")
    @ResponseWrapper(localName = "getProcessReqScheduleResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.GetProcessReqScheduleResponse")
    @WebMethod
    public com.stgmastek.core.comm.client.CResProcessRequestScheduleVO getProcessReqSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.stgmastek.core.comm.client.CReqProcessRequestScheduleVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "interruptBatch", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.InterruptBatch")
    @ResponseWrapper(localName = "interruptBatchResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.InterruptBatchResponse")
    @WebMethod
    public com.stgmastek.core.comm.client.CBaseResponseVO interruptBatch(
        @WebParam(name = "instruction", targetNamespace = "")
        com.stgmastek.core.comm.client.CReqInstruction instruction
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelCoreSchedule", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.CancelCoreSchedule")
    @ResponseWrapper(localName = "cancelCoreScheduleResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.CancelCoreScheduleResponse")
    @WebMethod
    public com.stgmastek.core.comm.client.CResProcessRequestScheduleVO cancelCoreSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.stgmastek.core.comm.client.CReqProcessRequestScheduleVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addCalendarLog", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.AddCalendarLog")
    @ResponseWrapper(localName = "addCalendarLogResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.AddCalendarLogResponse")
    @WebMethod
    public com.stgmastek.core.comm.client.CBaseResponseVO addCalendarLog(
        @WebParam(name = "reqCalendarLog", targetNamespace = "")
        com.stgmastek.core.comm.client.CReqCalendarLog reqCalendarLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addInstructionLog", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.AddInstructionLog")
    @ResponseWrapper(localName = "addInstructionLogResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.AddInstructionLogResponse")
    @WebMethod
    public com.stgmastek.core.comm.client.CBaseResponseVO addInstructionLog(
        @WebParam(name = "reqInstructionLog", targetNamespace = "")
        com.stgmastek.core.comm.client.CReqInstructionLog reqInstructionLog
    );

    @RequestWrapper(localName = "stopCoreComm", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.StopCoreComm")
    @ResponseWrapper(localName = "stopCoreCommResponse", targetNamespace = "http://services.server.comm.core.stgmastek.com/", className = "com.stgmastek.core.comm.client.StopCoreCommResponse")
    @WebMethod
    public void stopCoreComm();
}
