/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */

package com.stgmastek.monitor.services.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 09 10:30:14 IST 2010
 * Generated source version: 2.1.3
 * 
 */

public final class MonitorServices_MonitorServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.server.ws.monitor.stgmastek.com/", "MonitorServicesService");

    private MonitorServices_MonitorServicesPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MonitorServicesService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            }
        }
      
        MonitorServicesService ss = new MonitorServicesService(wsdlURL, SERVICE_NAME);
        MonitorServices port = ss.getMonitorServicesPort();  
        
        {
        System.out.println("Invoking userAuthentication...");
        com.stgmastek.monitor.services.client.UserCredentials _userAuthentication_userCredentials = null;
        com.stgmastek.monitor.services.client.ResUserDetails _userAuthentication__return = port.userAuthentication(_userAuthentication_userCredentials);
        System.out.println("userAuthentication.result=" + _userAuthentication__return);


        }
        {
        System.out.println("Invoking getCalendarData...");
        com.stgmastek.monitor.services.client.ReqCalendarVO _getCalendarData_calendarVO = null;
        com.stgmastek.monitor.services.client.ResCalendarVO _getCalendarData__return = port.getCalendarData(_getCalendarData_calendarVO);
        System.out.println("getCalendarData.result=" + _getCalendarData__return);


        }
        {
        System.out.println("Invoking retrieveParametersForReport...");
        com.stgmastek.monitor.services.client.Report _retrieveParametersForReport_report = null;
        com.stgmastek.monitor.services.client.ExecuteReport _retrieveParametersForReport__return = port.retrieveParametersForReport(_retrieveParametersForReport_report);
        System.out.println("retrieveParametersForReport.result=" + _retrieveParametersForReport__return);


        }
        {
        System.out.println("Invoking getMenuDetails...");
        com.stgmastek.monitor.services.client.UserProfile _getMenuDetails_userProfile = null;
        com.stgmastek.monitor.services.client.ResMenuDetails _getMenuDetails__return = port.getMenuDetails(_getMenuDetails_userProfile);
        System.out.println("getMenuDetails.result=" + _getMenuDetails__return);


        }
        {
        System.out.println("Invoking updateUserProfile...");
        com.stgmastek.monitor.services.client.ReqUserDetailsVO _updateUserProfile_reqUserDetailsVO = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _updateUserProfile__return = port.updateUserProfile(_updateUserProfile_reqUserDetailsVO);
        System.out.println("updateUserProfile.result=" + _updateUserProfile__return);


        }
        {
        System.out.println("Invoking checkInstructionLog...");
        com.stgmastek.monitor.services.client.ReqInstructionLog _checkInstructionLog_reqInstructionLog = null;
        com.stgmastek.monitor.services.client.ResInstructionVO _checkInstructionLog__return = port.checkInstructionLog(_checkInstructionLog_reqInstructionLog);
        System.out.println("checkInstructionLog.result=" + _checkInstructionLog__return);


        }
        {
        System.out.println("Invoking getBatchInfo...");
        com.stgmastek.monitor.services.client.ReqBatch _getBatchInfo_batch = null;
        com.stgmastek.monitor.services.client.ResBatchDataVO _getBatchInfo__return = port.getBatchInfo(_getBatchInfo_batch);
        System.out.println("getBatchInfo.result=" + _getBatchInfo__return);


        }
        {
        System.out.println("Invoking manageUser...");
        com.stgmastek.monitor.services.client.ReqUserDetailsVO _manageUser_reqUserDetailsVO = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _manageUser__return = port.manageUser(_manageUser_reqUserDetailsVO);
        System.out.println("manageUser.result=" + _manageUser__return);


        }
        {
        System.out.println("Invoking getBatchData...");
        com.stgmastek.monitor.services.client.ReqBatch _getBatchData_batch = null;
        com.stgmastek.monitor.services.client.ResBatchInfo _getBatchData__return = port.getBatchData(_getBatchData_batch);
        System.out.println("getBatchData.result=" + _getBatchData__return);


        }
        {
        System.out.println("Invoking getBatchObjectDetails...");
        com.stgmastek.monitor.services.client.ReqBatchDetails _getBatchObjectDetails_reqBatchDetails = null;
        com.stgmastek.monitor.services.client.ResBatchObjectVO _getBatchObjectDetails__return = port.getBatchObjectDetails(_getBatchObjectDetails_reqBatchDetails);
        System.out.println("getBatchObjectDetails.result=" + _getBatchObjectDetails__return);


        }
        {
        System.out.println("Invoking changePassword...");
        com.stgmastek.monitor.services.client.UserCredentials _changePassword_userCredentials = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _changePassword__return = port.changePassword(_changePassword_userCredentials);
        System.out.println("changePassword.result=" + _changePassword__return);


        }
        {
        System.out.println("Invoking getRoleData...");
        com.stgmastek.monitor.services.client.ResRoleDetailsVO _getRoleData__return = port.getRoleData();
        System.out.println("getRoleData.result=" + _getRoleData__return);


        }
        {
        System.out.println("Invoking stopBatch...");
        com.stgmastek.monitor.services.client.ReqInstructionLog _stopBatch_reqInstructionLog = null;
        com.stgmastek.monitor.services.client.ResInstallationVO _stopBatch__return = port.stopBatch(_stopBatch_reqInstructionLog);
        System.out.println("stopBatch.result=" + _stopBatch__return);


        }
        {
        System.out.println("Invoking getUserInstallationRoleDetails...");
        com.stgmastek.monitor.services.client.ReqUserDetailsVO _getUserInstallationRoleDetails_reqUserDetailsVO = null;
        com.stgmastek.monitor.services.client.ResUserDetailsVO _getUserInstallationRoleDetails__return = port.getUserInstallationRoleDetails(_getUserInstallationRoleDetails_reqUserDetailsVO);
        System.out.println("getUserInstallationRoleDetails.result=" + _getUserInstallationRoleDetails__return);


        }
        {
        System.out.println("Invoking getFaliedObjectDetails...");
        com.stgmastek.monitor.services.client.ReqListenerInfo _getFaliedObjectDetails_reqListenerInfo = null;
        com.stgmastek.monitor.services.client.ResFailedObjectVO _getFaliedObjectDetails__return = port.getFaliedObjectDetails(_getFaliedObjectDetails_reqListenerInfo);
        System.out.println("getFaliedObjectDetails.result=" + _getFaliedObjectDetails__return);


        }
        {
        System.out.println("Invoking getSecurityDetails...");
        com.stgmastek.monitor.services.client.UserProfile _getSecurityDetails_userProfile = null;
        com.stgmastek.monitor.services.client.ResUserProfile _getSecurityDetails__return = port.getSecurityDetails(_getSecurityDetails_userProfile);
        System.out.println("getSecurityDetails.result=" + _getSecurityDetails__return);


        }
        {
        System.out.println("Invoking getBatchCompletedData...");
        com.stgmastek.monitor.services.client.ReqSearchBatch _getBatchCompletedData_searchBatch = null;
        com.stgmastek.monitor.services.client.ResBatchInfo _getBatchCompletedData__return = port.getBatchCompletedData(_getBatchCompletedData_searchBatch);
        System.out.println("getBatchCompletedData.result=" + _getBatchCompletedData__return);


        }
        {
        System.out.println("Invoking getListenerInfo...");
        com.stgmastek.monitor.services.client.ReqBatch _getListenerInfo_batch = null;
        com.stgmastek.monitor.services.client.ResListenerVO _getListenerInfo__return = port.getListenerInfo(_getListenerInfo_batch);
        System.out.println("getListenerInfo.result=" + _getListenerInfo__return);


        }
        {
        System.out.println("Invoking getInstallationDetailsForBatch...");
        com.stgmastek.monitor.services.client.ReqBatch _getInstallationDetailsForBatch_batch = null;
        com.stgmastek.monitor.services.client.ResInstallationVO _getInstallationDetailsForBatch__return = port.getInstallationDetailsForBatch(_getInstallationDetailsForBatch_batch);
        System.out.println("getInstallationDetailsForBatch.result=" + _getInstallationDetailsForBatch__return);


        }
        {
        System.out.println("Invoking resetPassword...");
        com.stgmastek.monitor.services.client.UserProfile _resetPassword_userProfile = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _resetPassword__return = port.resetPassword(_resetPassword_userProfile);
        System.out.println("resetPassword.result=" + _resetPassword__return);


        }
        {
        System.out.println("Invoking getSystemInfo...");
        com.stgmastek.monitor.services.client.ReqBatch _getSystemInfo_batch = null;
        com.stgmastek.monitor.services.client.ResSystemDetails _getSystemInfo__return = port.getSystemInfo(_getSystemInfo_batch);
        System.out.println("getSystemInfo.result=" + _getSystemInfo__return);


        }
        {
        System.out.println("Invoking getInstallationData...");
        com.stgmastek.monitor.services.client.ReqBatch _getInstallationData_batch = null;
        com.stgmastek.monitor.services.client.ResInstallationVO _getInstallationData__return = port.getInstallationData(_getInstallationData_batch);
        System.out.println("getInstallationData.result=" + _getInstallationData__return);


        }
        {
        System.out.println("Invoking getInstallationsList...");
        com.stgmastek.monitor.services.client.ResInstallationVO _getInstallationsList__return = port.getInstallationsList();
        System.out.println("getInstallationsList.result=" + _getInstallationsList__return);


        }
        {
        System.out.println("Invoking retrieveReportDropDownOptionForCompany...");
        com.stgmastek.monitor.services.client.UserProfile _retrieveReportDropDownOptionForCompany_userProfile = null;
        com.stgmastek.monitor.services.client.ExecuteReport _retrieveReportDropDownOptionForCompany__return = port.retrieveReportDropDownOptionForCompany(_retrieveReportDropDownOptionForCompany_userProfile);
        System.out.println("retrieveReportDropDownOptionForCompany.result=" + _retrieveReportDropDownOptionForCompany__return);


        }
        {
        System.out.println("Invoking stopMonitorServices...");
        port.stopMonitorServices();


        }
        {
        System.out.println("Invoking getBatchEntityData...");
        com.stgmastek.monitor.services.client.ReqInstallationVO _getBatchEntityData_reqInstallationVO = null;
        com.stgmastek.monitor.services.client.ResInstallationEntitiesVO _getBatchEntityData__return = port.getBatchEntityData(_getBatchEntityData_reqInstallationVO);
        System.out.println("getBatchEntityData.result=" + _getBatchEntityData__return);


        }
        {
        System.out.println("Invoking getGraphData...");
        com.stgmastek.monitor.services.client.ReqBatch _getGraphData_batch = null;
        com.stgmastek.monitor.services.client.ResGraphVO _getGraphData__return = port.getGraphData(_getGraphData_batch);
        System.out.println("getGraphData.result=" + _getGraphData__return);


        }
        {
        System.out.println("Invoking runBatch...");
        com.stgmastek.monitor.services.client.ReqInstructionLog _runBatch_reqInstructionLog = null;
        com.stgmastek.monitor.services.client.ResBatchInfo _runBatch__return = port.runBatch(_runBatch_reqInstructionLog);
        System.out.println("runBatch.result=" + _runBatch__return);


        }
        {
        System.out.println("Invoking checkCompatibility...");
        com.stgmastek.monitor.services.client.ReqVersionVO _checkCompatibility_version = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _checkCompatibility__return = port.checkCompatibility(_checkCompatibility_version);
        System.out.println("checkCompatibility.result=" + _checkCompatibility__return);


        }
        {
        System.out.println("Invoking getCalendars...");
        com.stgmastek.monitor.services.client.ReqCalendarVO _getCalendars_calendarVO = null;
        com.stgmastek.monitor.services.client.ResCalendarVO _getCalendars__return = port.getCalendars(_getCalendars_calendarVO);
        System.out.println("getCalendars.result=" + _getCalendars__return);


        }
        {
        System.out.println("Invoking processRequest...");
        com.stgmastek.monitor.services.client.ExecuteReport _processRequest_executeReport = null;
        com.stgmastek.monitor.services.client.ReqInstructionLog _processRequest_reqInstructionLog = null;
        com.stgmastek.monitor.services.client.ResBatchInfo _processRequest__return = port.processRequest(_processRequest_executeReport, _processRequest_reqInstructionLog);
        System.out.println("processRequest.result=" + _processRequest__return);


        }
        {
        System.out.println("Invoking defineCalendar...");
        com.stgmastek.monitor.services.client.ReqCalendarVO _defineCalendar_calendarVO = null;
        com.stgmastek.monitor.services.client.BaseResponseVO _defineCalendar__return = port.defineCalendar(_defineCalendar_calendarVO);
        System.out.println("defineCalendar.result=" + _defineCalendar__return);


        }
        {
        System.out.println("Invoking retrieveDropDownEntries...");
        java.util.List<com.stgmastek.monitor.services.client.ConfigParameter> _retrieveDropDownEntries_dropDownIdentifierList = null;
        com.stgmastek.monitor.services.client.ResDropDownEntry _retrieveDropDownEntries__return = port.retrieveDropDownEntries(_retrieveDropDownEntries_dropDownIdentifierList);
        System.out.println("retrieveDropDownEntries.result=" + _retrieveDropDownEntries__return);


        }

        System.exit(0);
    }

}
