/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */
package com.stgmastek.monitor.services.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 09 10:30:15 IST 2010
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", name = "MonitorServices")
@XmlSeeAlso({ObjectFactory.class})
public interface MonitorServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "userAuthentication", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.UserAuthentication")
    @ResponseWrapper(localName = "userAuthenticationResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.UserAuthenticationResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResUserDetails userAuthentication(
        @WebParam(name = "userCredentials", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserCredentials userCredentials
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCalendarData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetCalendarData")
    @ResponseWrapper(localName = "getCalendarDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetCalendarDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResCalendarVO getCalendarData(
        @WebParam(name = "calendarVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqCalendarVO calendarVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveParametersForReport", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveParametersForReport")
    @ResponseWrapper(localName = "retrieveParametersForReportResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveParametersForReportResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ExecuteReport retrieveParametersForReport(
        @WebParam(name = "Report", targetNamespace = "")
        com.stgmastek.monitor.services.client.Report report
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMenuDetails", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetMenuDetails")
    @ResponseWrapper(localName = "getMenuDetailsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetMenuDetailsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResMenuDetails getMenuDetails(
        @WebParam(name = "userProfile", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserProfile userProfile
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUserProfile", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.UpdateUserProfile")
    @ResponseWrapper(localName = "updateUserProfileResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.UpdateUserProfileResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO updateUserProfile(
        @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqUserDetailsVO reqUserDetailsVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkInstructionLog", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.CheckInstructionLog")
    @ResponseWrapper(localName = "checkInstructionLogResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.CheckInstructionLogResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstructionVO checkInstructionLog(
        @WebParam(name = "reqInstructionLog", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqInstructionLog reqInstructionLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchInfo", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchInfo")
    @ResponseWrapper(localName = "getBatchInfoResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchInfoResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchDataVO getBatchInfo(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "manageUser", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ManageUser")
    @ResponseWrapper(localName = "manageUserResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ManageUserResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO manageUser(
        @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqUserDetailsVO reqUserDetailsVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchData")
    @ResponseWrapper(localName = "getBatchDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchInfo getBatchData(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchObjectDetails", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchObjectDetails")
    @ResponseWrapper(localName = "getBatchObjectDetailsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchObjectDetailsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchObjectVO getBatchObjectDetails(
        @WebParam(name = "reqBatchDetails", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatchDetails reqBatchDetails
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ChangePasswordResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO changePassword(
        @WebParam(name = "userCredentials", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserCredentials userCredentials
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetRoleData")
    @ResponseWrapper(localName = "getRoleDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetRoleDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResRoleDetailsVO getRoleData();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "stopBatch", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.StopBatch")
    @ResponseWrapper(localName = "stopBatchResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.StopBatchResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstallationVO stopBatch(
        @WebParam(name = "reqInstructionLog", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqInstructionLog reqInstructionLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserInstallationRoleDetails", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetUserInstallationRoleDetails")
    @ResponseWrapper(localName = "getUserInstallationRoleDetailsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetUserInstallationRoleDetailsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResUserDetailsVO getUserInstallationRoleDetails(
        @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqUserDetailsVO reqUserDetailsVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFaliedObjectDetails", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetFaliedObjectDetails")
    @ResponseWrapper(localName = "getFaliedObjectDetailsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetFaliedObjectDetailsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResFailedObjectVO getFaliedObjectDetails(
        @WebParam(name = "reqListenerInfo", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqListenerInfo reqListenerInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSecurityDetails", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetSecurityDetails")
    @ResponseWrapper(localName = "getSecurityDetailsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetSecurityDetailsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResUserProfile getSecurityDetails(
        @WebParam(name = "userProfile", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserProfile userProfile
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchCompletedData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchCompletedData")
    @ResponseWrapper(localName = "getBatchCompletedDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchCompletedDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchInfo getBatchCompletedData(
        @WebParam(name = "searchBatch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqSearchBatch searchBatch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListenerInfo", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetListenerInfo")
    @ResponseWrapper(localName = "getListenerInfoResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetListenerInfoResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResListenerVO getListenerInfo(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInstallationDetailsForBatch", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationDetailsForBatch")
    @ResponseWrapper(localName = "getInstallationDetailsForBatchResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationDetailsForBatchResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstallationVO getInstallationDetailsForBatch(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ResetPasswordResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO resetPassword(
        @WebParam(name = "userProfile", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserProfile userProfile
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSystemInfo", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetSystemInfo")
    @ResponseWrapper(localName = "getSystemInfoResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetSystemInfoResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResSystemDetails getSystemInfo(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInstallationData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationData")
    @ResponseWrapper(localName = "getInstallationDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstallationVO getInstallationData(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInstallationsList", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationsList")
    @ResponseWrapper(localName = "getInstallationsListResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetInstallationsListResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstallationVO getInstallationsList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveReportDropDownOptionForCompany", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveReportDropDownOptionForCompany")
    @ResponseWrapper(localName = "retrieveReportDropDownOptionForCompanyResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveReportDropDownOptionForCompanyResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ExecuteReport retrieveReportDropDownOptionForCompany(
        @WebParam(name = "UserProfile", targetNamespace = "")
        com.stgmastek.monitor.services.client.UserProfile userProfile
    );

    @RequestWrapper(localName = "stopMonitorServices", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.StopMonitorServices")
    @ResponseWrapper(localName = "stopMonitorServicesResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.StopMonitorServicesResponse")
    @WebMethod
    public void stopMonitorServices();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchEntityData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchEntityData")
    @ResponseWrapper(localName = "getBatchEntityDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetBatchEntityDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResInstallationEntitiesVO getBatchEntityData(
        @WebParam(name = "reqInstallationVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqInstallationVO reqInstallationVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGraphData", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetGraphData")
    @ResponseWrapper(localName = "getGraphDataResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetGraphDataResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResGraphVO getGraphData(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "runBatch", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RunBatch")
    @ResponseWrapper(localName = "runBatchResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RunBatchResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchInfo runBatch(
        @WebParam(name = "reqInstructionLog", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqInstructionLog reqInstructionLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkCompatibility", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.CheckCompatibility")
    @ResponseWrapper(localName = "checkCompatibilityResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.CheckCompatibilityResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO checkCompatibility(
        @WebParam(name = "version", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqVersionVO version
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCalendars", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetCalendars")
    @ResponseWrapper(localName = "getCalendarsResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.GetCalendarsResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResCalendarVO getCalendars(
        @WebParam(name = "calendarVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqCalendarVO calendarVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processRequest", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ProcessRequest")
    @ResponseWrapper(localName = "processRequestResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.ProcessRequestResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResBatchInfo processRequest(
        @WebParam(name = "ExecuteReport", targetNamespace = "")
        com.stgmastek.monitor.services.client.ExecuteReport executeReport,
        @WebParam(name = "ReqInstructionLog", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqInstructionLog reqInstructionLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "defineCalendar", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.DefineCalendar")
    @ResponseWrapper(localName = "defineCalendarResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.DefineCalendarResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.BaseResponseVO defineCalendar(
        @WebParam(name = "calendarVO", targetNamespace = "")
        com.stgmastek.monitor.services.client.ReqCalendarVO calendarVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "retrieveDropDownEntries", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveDropDownEntries")
    @ResponseWrapper(localName = "retrieveDropDownEntriesResponse", targetNamespace = "http://services.server.ws.monitor.stgmastek.com/", className = "com.stgmastek.monitor.services.client.RetrieveDropDownEntriesResponse")
    @WebMethod
    public com.stgmastek.monitor.services.client.ResDropDownEntry retrieveDropDownEntries(
        @WebParam(name = "DropDownIdentifierList", targetNamespace = "")
        java.util.List<com.stgmastek.monitor.services.client.ConfigParameter> dropDownIdentifierList
    );
}
