Insert into CONFIGURATION (CODE1,CODE2,CODE3,VALUE,VALUE_TYPE,DESCRIPTION) values ('CORE','ICD_SERVICE','USER_ID','&ICD_Service_UserId','S','User id for ICDService');
Insert into CONFIGURATION (CODE1,CODE2,CODE3,VALUE,VALUE_TYPE,DESCRIPTION) values ('CORE','ICD_SERVICE','PASSWORD','&ICD_Service_Password','S','Password for ICDService');

ALTER TABLE LOG MODIFY OBJECT_NAME VARCHAR2(100);