/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */
package com.stgmastek.monitor.comm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Jan 28 17:05:17 IST 2013
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", name = "MonitorCommServices")
@XmlSeeAlso({ObjectFactory.class})
public interface MonitorCommServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateSystemInformation", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateSystemInformation")
    @ResponseWrapper(localName = "updateSystemInformationResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateSystemInformationResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO updateSystemInformation(
        @WebParam(name = "systemInfo", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqSystemInfo systemInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateBatch", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatch")
    @ResponseWrapper(localName = "updateBatchResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatchResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO updateBatch(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqBatch batch
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateInstructionLog", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateInstructionLog")
    @ResponseWrapper(localName = "updateInstructionLogResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateInstructionLogResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO updateInstructionLog(
        @WebParam(name = "instructionLog", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqInstructionLog instructionLog
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refreshProcessRequestSchedule", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.RefreshProcessRequestSchedule")
    @ResponseWrapper(localName = "refreshProcessRequestScheduleResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.RefreshProcessRequestScheduleResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO refreshProcessRequestSchedule(
        @WebParam(name = "requestScheduleVO", targetNamespace = "")
        com.stgmastek.monitor.comm.client.CReqProcessRequestScheduleVO requestScheduleVO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addBatch", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.AddBatch")
    @ResponseWrapper(localName = "addBatchResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.AddBatchResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO addBatch(
        @WebParam(name = "batch", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqBatch batch
    );

    @RequestWrapper(localName = "stopMonitorComm", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.StopMonitorComm")
    @ResponseWrapper(localName = "stopMonitorCommResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.StopMonitorCommResponse")
    @WebMethod
    public void stopMonitorComm();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateBatchProgress", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatchProgress")
    @ResponseWrapper(localName = "updateBatchProgressResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatchProgressResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO updateBatchProgress(
        @WebParam(name = "reqBatchProgress", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqBatchProgress reqBatchProgress
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateBatchLog", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatchLog")
    @ResponseWrapper(localName = "updateBatchLogResponse", targetNamespace = "http://services.server.comm.monitor.stgmastek.com/", className = "com.stgmastek.monitor.comm.client.UpdateBatchLogResponse")
    @WebMethod
    public com.stgmastek.monitor.comm.client.MBaseResponseVO updateBatchLog(
        @WebParam(name = "requestBatchLog", targetNamespace = "")
        com.stgmastek.monitor.comm.client.MReqBatchLog requestBatchLog
    );
}
