/*
 * Copyright (c) 2014 Mastek Ltd. All rights reserved.
 * 
 * This file is part of JBEAM. JBEAM is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * JBEAM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for the specific language governing permissions and 
 * limitations.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with JBEAM. If not, see <http://www.gnu.org/licenses/>.
 */

package com.stgmastek.monitor.comm.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Jan 28 17:05:17 IST 2013
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "MonitorCommServicesService", 
                  wsdlLocation = "http://172.16.246.108:11002/MonitorCommServices?wsdl",
                  targetNamespace = "http://services.server.comm.monitor.stgmastek.com/") 
public class MonitorCommServicesService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://services.server.comm.monitor.stgmastek.com/", "MonitorCommServicesService");
    public final static QName MonitorCommServicesPort = new QName("http://services.server.comm.monitor.stgmastek.com/", "MonitorCommServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.246.108:11002/MonitorCommServices?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://172.16.246.108:11002/MonitorCommServices?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MonitorCommServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MonitorCommServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorCommServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns MonitorCommServices
     */
    @WebEndpoint(name = "MonitorCommServicesPort")
    public MonitorCommServices getMonitorCommServicesPort() {
        return super.getPort(MonitorCommServicesPort, MonitorCommServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorCommServices
     */
    @WebEndpoint(name = "MonitorCommServicesPort")
    public MonitorCommServices getMonitorCommServicesPort(WebServiceFeature... features) {
        return super.getPort(MonitorCommServicesPort, MonitorCommServices.class, features);
    }

}
